### ISSUE TITLE
Canary should detect if a message is pasted into a where a record is expected

### ISSUE THREAD

**Issue by pkmitre** [nightingaleproject/canary#104]
If a user pastes a message where a bare record is expected Canary silently tries to process it and essentially pulls out no data. Canary could either

1. Automatically pull out the record (convenient but potentially confusing) or
2. Notify the user that a message was provided where a record was expected

**Comment by wswarr** [comment]
![image](https://github.com/nightingaleproject/canary/assets/8007087/4ffc98a4-133e-4e43-89ae-83dcf51367c5)
Error added, attached image displays error

**Comment by whichwit** [comment]
Will this cause issues for workflows where a message is expected but a record is pasted?
