### ISSUE TITLE
Canary easily allows the connectathon records to be downloaded

### ISSUE THREAD

**Issue by pkmitre** [nightingaleproject/canary#107]
The Canary Record tools should have a tool for just downloading the Connectathon test records. The tool should

Take the user to a page that (similar to the connecathon message testing page) allows the user to
1. select the desired connectathon record
2. select the certificate number and jurisdiction
3. view the record on the page with the option to download it

<img width="1215" alt="Screen Shot 2023-01-23 at 5 07 56 PM" src="https://user-images.githubusercontent.com/3720400/214160860-dd0e4139-781a-4416-9e5f-b07f7755be62.png">

Note that this flow is substantially identical to the connectathon message testing flow, just with slightly different wording on the page (e.g., just informing the user they can view and download the record rather than instructing the user to enter the record into their system) and so should leverage the existing implementation pieces as much as possible.

**Comment by whichwit** [comment]
There is already a `Download as File` action button available when viewing the record. Is it sufficient to use this feature to download the test records?

**Comment by whichwit** [comment]
Use `Download as File` function.
