### ISSUE TITLE
Add FSH InstanceOf correction tool to Canary to aid in pre-certification process

### ISSUE THREAD

**Issue by johnarleyburns** [nightingaleproject/canary#120]
Background:

https://community.intersystems.com/post/lets-create-fhir-profile-using-sushi-part-1

After a Death Record Submission Message JSON is converted to FSH format, the FSH "InstanceOf" fields are generic FHIR types, such as "Patient".  However, to properly validate against the VRDR IG, the actual IG type from the meta.profile URL is needed, such as "Decedent".

Create a Canary Menu Item to take in a Death Record Submission Message converted FSH file and output an FSH file with each InstanceOf field properly set.

**Comment by whichwit** [comment]
Completed via #248
