### ISSUE TITLE
Add FSH <-> JSON conversion to Canary 

### ISSUE THREAD

**Issue by johnarleyburns** [nightingaleproject/canary#121]
Background: https://www.npmjs.com/package/fsh-sushi

Currently there is on online resource to convert FSH files to and from JSON on the web:

https://fshschool.org/FSHOnline/#/

However, Canary lacks this feature.  Please add a menu item to Canary to provide the same functionality.  It is important we have this within Canary, because for VRDR IG validation purposes, we want to do other post-processing in Canary such as updating the InstanceOf field and adding the component type instead of numbered components.

**Comment by wswarr** [comment]
Additional comments / requirements:

Update title to "FHIR to FSH Converter"
Alert user that it will take a few seconds to load
Dedicate page to FSH hide the JSON, XML and IJE tabs
Remove the Decedent display etc.
Update Whole message content. Messaging etc.
Work on only sending the record to the api, not the whole message

Possibly add check box to show errors / warnings
Hide Errors:  or Warnings:  if blank

**Comment by whichwit** [comment]
Completed via #248
