### ISSUE TITLE
Add description to unknown record and message properties.

### ISSUE THREAD

**Issue by whichwit** [nightingaleproject/canary#159]
Additional properties were added to DeathRecord (.NET) class. Need to add description for new and existing properties without description so the descriptions can be included in the validation report.

**Comment by wswarr** [comment]
Based on this document:
https://build.fhir.org/ig/HL7/vrdr/DeathRecordDataDictionary.html
The messageDescription in Message.cs will be added to using:
IJE Name == Key
Description == Value
in the existing dictionary
